Create usb-platform-upgrade.sh
erigones/esdc-ce pull request #520
Opened 2020-11-07 11:59 UTC by marcheschi

Adapt smartos platform upgrade to work with Danube Cloud
Add the ability to download tgz without checking md5
It uses the /tmp folder to store files 
Paolo

2020-11-07 18:01 UTC, YanChii requested changes

2020-11-08 09:05 UTC, marcheschi commented on bin/eslib/usb-platform-upgrade.sh
> +mkdir /zones/tmp
ok

2020-11-08 09:45 UTC, marcheschi commented on bin/eslib/usb-platform-upgrade.sh
> +    platform_url="$latest_path/platform-release-$header-$version.tgz"
For the moment I removed the joyent url, but to use DC url we have to define a static latest path, in order to be sure to download the latest platform for upgrade

2020-11-08 09:47 UTC, marcheschi commented on bin/eslib/usb-platform-upgrade.sh
> +mkdir usb
to create the mount point

2020-11-08 09:49 UTC, marcheschi commented
I tried the latest committed script on DC it works:
[root@m2c (pacs) /zones/PAOLO]# ./platform-upgrade -u https://download.danube.cloud/esdc/factory/platform/platform-20201105T132431Z.tgz -f
Brand= esdc
Actual kernel=  20201105T132431Z
New Version=  20201105T132431Z
Already on latest version (20201105T132431Z).
Downloading platform-20201105T132431Z.tgz... OK
md5sum= ||
Extracting latest platform... OK
Marking release version... OK
Checking current boot device... detected c1t0d0, GPT labelusb path=  /dev/dsk/c1t0d0s2
, mounted, OK
Updating platform on boot device... OK
Remounting boot device... OK
Verifying kernel checksum on boot device... OK
Verifying boot_archive checksum on boot device... OK
Activating new platform on /dev/dsk/c1t0d0s2... please wait...Finished: OK

Boot device upgraded. To do:

 1) Sanity check the contents of /tmp/tmp.e6aM9j/usb
 2) umount /dev/dsk/c1t0d0s2
 3) reboot
[root@m2c (pacs) /zones/PAOLO]#

2020-11-08 16:32 UTC, YanChii approved these changes

2020-11-08 16:32 UTC, YanChii commented on bin/eslib/usb-platform-upgrade.sh
> +mkdir usb
Ah, I've missed that there's no `$` before `usb` :)

2020-11-08 16:34 UTC, merged